### ISSUE TITLE
Wireshark 4.2.4 Fedora 40 - Error during loading

### ISSUE THREAD

**Issue by SebaLukas** [dspace-group/dsV2Gshark#13]
Hi :)

I can't use your Wireshark plugin (version 1.4.0) under Fedora 40 and Wireshark 4.2.4.

When starting Wireshark I get this error message:

![Wireshark_Lua_Error](https://github.com/dspace-group/dsV2Gshark/assets/45936573/80ed12a1-e6f3-44df-a7a6-c64d2382736a)

I have moved the files from [dsV2Gshark_Files_Linux_x86_64.zip](https://github.com/dspace-group/dsV2Gshark/releases/download/v1.4.0/dsV2Gshark_Files_Linux_x86_64.zip) to the `~/.local/lib/wirshark` folder as described and removed all other plugins:
```
wireshark/
├── plugins
│   ├── v2gmsg.lua
│   ├── v2gsdp.lua
│   ├── v2gshared.lua
│   ├── v2gtlssecret.lua
│   └── v2gtp.lua
├── v2gLuaDecoder.so
└── v2gX509CertInfos.so
```

The plugin works for me under Ubuntu 22.04 and Wireshark 3.6.2.

Many thanks in advance!

**Comment by adoebber** [comment]
Sorry for the inconvenience. We will try to find a solution that works for (most) Linux distributions. In the meantime: Can you try to build the libraries yourself as described in #10?

**Comment by SebaLukas** [comment]
Thanks for the answer, I'll try to build Wireshark myself!
The good thing is that with distrobox and ubuntu 22.04 I have a working Wireshark with your plugin if it doesn't work.
