### ISSUE TITLE
WireShark Linux Ubuntu 22.04

### ISSUE THREAD

**Issue by dfdias** [dspace-group/dsV2Gshark#7]
Hello

When I try to open a capture file there is a dissector problem at
Lua: Error during execution of initialization:
 /home/duarte/.local/lib/wireshark/plugins/v2gmsg.lua:133: bad argument #2 to 'add' (DissectorTable_add: must be either Proto or Dissector)

 /home/duarte/.local/lib/wireshark/plugins/v2gmsg.lua: attempt to index global 'p_v2gmsg' (a nil value)

I know the windows version works, so do you have any reports in similar problems ?

Thanks in advance.

**Comment by barsnick** [comment]
Same here. I get it as a modal popup (which hides some of the message), with another message popup on top. But the dissector does seem to work.

Did you get it to work with Wireshark 4.2? I needed to change a lot of code for the binary plugin to load properly.

**Comment by TGruett** [comment]
UPDATE:
if finally managed to get the same error message:
`~/.local/lib/wireshark/plugins/v2gmsg.lua:133: bad argument https://github.com/dspace-group/dsV2Gshark/pull/2 to 'add' (DissectorTable_add: must be either Proto or Dissector)`

This only seems to happen if you put the *.lua file in the `~/.local/lib/wireshark` directory. I've tested the Linux plugin version by putting the *.lua files in `/usr/lib/x86_64-linux-gnu/wireshark` or `/usr/local/lib/wireshark` (whatever `$whereis wireshark` told me).

I will take a closer look at this, but for now i recommend to remove the files from the `~/.local/lib/wireshark` and use the directory which `whereis wireshark` gives you, which already has a plugin directory in it.

**Comment by barsnick** [comment]
> This only seems to happen if you put the *.lua file in the `~/.local/lib/wireshark` directory.

Interesting, I would never have guessed this. Same for the shared objects - these can usually be located in `~/.local/lib/wireshark/plugins.bak/{3.6,4.0}/epan/`, making it a classical "plugin", unlike an integrated dissector. Using this location does not work for the libraries in your binary package (at least for Wireshark 4.x) or compiled from source, as these "local" binaries require additional symbols. (I have a local patch for that.) It would be great to be able to use this like a classic plugin (just through the files into these user-owned locations).

**Comment by dfdias** [comment]
Thanks Mates :) well done  :+1:
